### ISSUE TITLE
Make the changes in  README.md file

### ISSUE THREAD

**Issue by Tufailahmed-Bargir** [oskccy/chatGPT-clone#1]
when i cloned your repo it is showing open in browser 3000,instead you are defined the port 8000
![image](https://github.com/oskccy/chatGPT_clone/assets/142114244/0b2de675-f4b6-4717-8a56-651ec980b5fe)

**Comment by oskccy** [comment]
3000 is for frontend, 8000 is for backend. they run seperately on different ports. thank you!!
